force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia do produto (alternativo ao produto).</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto do frete (alternativo à hierarquia de produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HierarquiaProduto__c/HierarquiaProduto__c.object-meta.xml
<CustomObject>
    <description>Hierarquia a que produtos pertencem</description>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Nome da Hierarquia de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>País</description>
    <label>País</label>
    <nameField>
        <label>Nome do País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/helper/FreteHelper.cls
public with sharing class FreteHelper {
    
    public static void impedirDuplicidade(List<Frete__c> newFretes) {
        Set<Id> idsLocalidade = new Set<Id>();
        Set<Id> idsProduto = new Set<Id>();
        Set<String> freteLocProdPair = new Set<String>();

        for (Frete__c frete : newFretes) {
            Id localidade = getLocalidadeId(frete);
            Id produto = getProdutoId(frete);

            if (freteLocProdPair.add(KeyStringGenerator.createStringFromKeys(localidade, produto))) {
                idsLocalidade.add(localidade);
                idsProduto.add(produto);
            } else {
                frete.addError('Este frete é duplicata de outro nesta mesma inserção.');
            }
        }

        Set<String> locProdutoPairOrg = new Set<String>();
        for (Frete__c freteOrg : [SELECT Id, Cidade__c, Estado__c, Pais__c, Product__c, HierarquiaProduto__c
                                        FROM Frete__c 
                                        WHERE ((Cidade__c IN :idsLocalidade OR Estado__c IN :idsLocalidade OR Pais__c IN :idsLocalidade) 
                                            AND (Product__c IN :idsProduto OR HierarquiaProduto__c IN :idsProduto))]) {
            locProdutoPairOrg.add(KeyStringGenerator.createStringFromKeys(getLocalidadeId(freteOrg), getProdutoId(freteOrg)));
        }

        for (Frete__c newFrete : newFretes) {
            if (locProdutoPairOrg.contains(KeyStringGenerator.createStringFromKeys(getLocalidadeId(newFrete), getProdutoId(newFrete)))) {
                newFrete.addError('Já existe um frete para esse produto/hierarquia nesse estado.');
                continue;
            }
        }
    }

    private static Id getLocalidadeId(Frete__c frete) {
        return String.isNotBlank(frete.Cidade__c) ? frete.Cidade__c :
                                String.isNotBlank(frete.Estado__c) ? frete.Estado__c : 
                                    frete.Pais__c;
    }

    private static Id getProdutoId(Frete__c frete) {
        return String.isNotBlank(frete.Product__c) ? frete.Product__c : frete.HierarquiaProduto__c;
    }

}