force-app/main/default/objects/HierarquiaProduto__c/HierarquiaProduto__c.object-meta.xml
<CustomObject>
    <description>Hierarquia a que produtos pertencem</description>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Nome da Hierarquia de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HierarquiaProduto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <description>Código de cadastro da hierarquia.</description>
    <label>Código</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <description>Código de cadastro do produto.</description>
    <label>Codigo</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/CustoProducao__c.field-meta.xml
<CustomField>
    <fullName>CustoProducao__c</fullName>
    <label>Custo de Produção</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hierarquia do produto</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/helper/ProductHelper.cls
public with sharing class ProductHelper {

    public static void putCustomCodeInProductCode(List<Product2> products) {
        for (Product2 product : products) {
            product.ProductCode = product.Codigo__c;
        }
    }

    public static void createPriceBookEntryForNewProducts(List<Product2> products, Pricebook2 pricebook) {

        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        for (Product2 product : products) {
            pricebookEntries.add(PricebookHelper.createPricebookEntryForInsertion(pricebook, product));
        }

        System.debug(products);
        System.debug(pricebookEntries);

        Database.insert(pricebookEntries, false);

        System.debug(pricebookEntries[0].getErrors());
    }

    public static List<Product2> queryProductsWithIds(Set<Id> ids) {
        return [SELECT Id, HierarquiaProduto__c, CustoProducao__c
                FROM Product2
                WHERE Id IN :ids];
    }

}