force-app/main/default/objects/DevUser__c/DevUser__c.object-meta.xml
<CustomObject>
    <label>Dev User</label>
    <nameField>
        <label>Dev User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DevUser__c/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DevUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DevUser__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DevUserHelper.cls
public with sharing class DevUserHelper {
    
    public static List<DevUser__c> getDevUsersGithubData(List<DevUser__c> devUsers) {
        List<DevUser__c> devUsersWithData = new List<DevUser__c>();

        for (DevUser__c iDevUser : devUsers) {
            String responsePayload = getGithubUserData(iDevUser.Login__c);

            Map<String,Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(responsePayload);

            iDevUser.ExternalId__c = (Integer) responseMap.get('id');
            iDevUser.Type__c = (String) responseMap.get('type');
            iDevUser.Bio__c = (String) responseMap.get('bio');

            devUsersWithData.add(iDevUser);
        }

        return devUsersWithData;
    }

    public static String getGithubUserData(String login) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.github.com/users/' + login);
        request.setMethod('GET');
        request.setHeader('Accept', 'application/vnd.github+json');

        HttpResponse response = http.send(request);

        System.debug('Callout response: ' + response);

        System.debug('Body: ' + response.getBody());

        return response.getBody();
    }

}