force-app/main/default/objects/DevUser__c/DevUser__c.object-meta.xml
<CustomObject>
    <label>Dev User</label>
    <nameField>
        <label>Dev User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dev Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DevUser__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DevUserDataRetriever.cls
public with sharing class DevUserDataRetriever implements Database.Batchable<SObject>, Database.AllowsCallouts {

    Set<Id> devUserIds;

    public DevUserDataRetriever(Set<Id> devUserIds) {
        this.devUserIds = devUserIds;
    }

    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        String query = 'SELECT Id, Login__c FROM DevUser__c WHERE Id IN (';
        for (Id id : devUserIds) {
            query += '\'' + id + '\',';
        }
        query = query.removeEnd(',');
        query += ')';

        System.debug('Batch query: ' + query);

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext batchableContext, List<sObject> scope) {
        List<DevUser__c> devUsersWithData = DevUserHelper.getDevUsersGithubData(scope);

        System.debug('DevUsers with Data: ');
        System.debug(devUsersWithData);

        Database.update(devUsersWithData);
    }

    public void finish(Database.BatchableContext batchableContext) {

    }

}