force-app/main/default/objects/CentroDistribuicao__c/CentroDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável por frete.</description>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome do Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável pelo pedido.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta associada à margem (alternativa ao grupo de contas).</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição associado à margem.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual a margem é aplicada (alternativo à Hierarquia de Produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da margem.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test/MargemTeste.cls
@IsTest
public with sharing class MargemTeste {
    
    @IsTest 
    static void testBulkDuplicityOnInsert() {
        Margem__c margin1 = TestDataFactory.createMargin(false); 
        Margem__c margin2 = margin1.clone();
        List<Margem__c> margins = new List<Margem__c>{margin1, margin2};

        List<Database.SaveResult> results = Database.insert(margins, false);

        Assert.isTrue(results[0].isSuccess(), 'Houve erro no primeiro registro');
        Assert.isFalse(results[1].isSuccess(), 'A duplicata foi inserida');
        Assert.isTrue(results[1].getErrors().size() > 0, 'Não houve erro no registro duplicado');
        Assert.areEqual('Esta margem é duplicata de outra nesta mesma inserção.', results[1].getErrors()[0].getMessage(), 'Mensagem de erro discrepante.');
    }


    @IsTest 
    static void testOrgDuplicityOnInsert() {
        Margem__c margin1 = TestDataFactory.createMargin(true); 
        Margem__c margin2 = margin1.clone();

        Database.SaveResult result = Database.insert(margin2, false);

        Assert.isFalse(result.isSuccess(), 'A duplicata foi inserida');
        Assert.isTrue(result.getErrors().size() > 0, 'Não houve erro no registro duplicado');
        Assert.areEqual('Já existe uma margem para esse produto/hierarquia e conta/grupo nessa localidade.', result.getErrors()[0].getMessage(), 'Mensagem de erro discrepante.');
    }

    @IsTest 
    static void testQuery() {
        Product2 product = TestDataFactory.createProduct(true);
        Account account = TestDataFactory.createAccount(true);
        Estado__c state = TestDataFactory.createState(true);
        DistributionCenter__c distCenter1 = TestDataFactory.createDistCenter(true);
        DistributionCenter__c distCenter2 = TestDataFactory.createDistCenter(true);

        Margem__c margin1 = TestDataFactory.createMargin(product.Id, account.Id, state.Id, distCenter1.Id, true);
        Margem__c margin2 = TestDataFactory.createMargin(product.Id, account.Id, state.Id, distCenter2.Id, true);

        List<Margem__c> margins = MargemHelper.queryMarginWithFields(new Set<Id>(), new Set<Id>{state.Id}, new Set<Id>(), new Set<Id>{product.Id}, new Set<Id>(), new Set<Id>{account.Id}, new Set<Id>(), new Set<Id>{distCenter1.Id});

        Assert.areEqual(1, margins.size(), 'A query não retornou apenas um registro');
        Assert.areEqual(margin1.Id, margins[0].Id, 'O registro retornado pela query não é o esperado');
    }

    @IsTest 
    static void testQueryApprovedWithBlockedRecord() {
        Margem__c margin2 = TestDataFactory.createMargin(false);
        Margem__c margin1 = TestDataFactory.createMargin(false);
        margin2.Status__c = 'Bloqueado';
        Database.insert(new List<Margem__c>{margin1, margin2});

        List<Margem__c> margins = MargemHelper.queryApprovedMarginWithFields(new Set<Id>{margin1.Cidade__c, margin2.Cidade__c}, new Set<Id>(), new Set<Id>(),new Set<Id>{margin1.Product__c, margin2.Product__c}, new Set<Id>(), new Set<Id>{margin1.Account__c, margin2.Account__c}, new Set<Id>(), new Set<Id>{margin1.CentroDistribuicao__c, margin2.CentroDistribuicao__c});

        Assert.areEqual(1, margins.size(), 'A query não retornou apenas um registro');
        Assert.areEqual(margin1.Id, margins[0].Id, 'O registro retornado pela query não é o esperado');
    }

    @IsTest 
    static void testGetStringKeyMap() {
        Margem__c margin1 = TestDataFactory.createMargin(false);
        Margem__c margin2 = TestDataFactory.createMargin(false);
        List<Margem__c> margins = new List<Margem__c>{margin1, margin2};

        Map<String, Margem__c> mapStringKeyXMargin = MargemHelper.getMapStringKeyXMargin(margins);

        Assert.areEqual(margin1, mapStringKeyXMargin.get(KeyStringGenerator.createStringKeyFromIds(margin1.Cidade__c, margin1.Product__c, margin1.Account__c, margin1.CentroDistribuicao__c)));
        Assert.areEqual(margin2, mapStringKeyXMargin.get(KeyStringGenerator.createStringKeyFromIds(margin2.Cidade__c, margin2.Product__c, margin2.Account__c, margin2.CentroDistribuicao__c)));
    }
}