force-app/main/default/objects/CentroDistribuicao__c/CentroDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável por frete.</description>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome do Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável pelo pedido.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição aonde o pedido será enviado.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto do frete (alternativo à hierarquia de produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/FreteTest.cls
@IsTest
private with sharing class FreteTest {
    
    @IsTest 
    static void testBulkDuplicityOnInsert() {
        Test.startTest();

        Frete__c freight1 = TestDataFactory.createFreight(false); 
        Frete__c freight2 = freight1.clone();
        List<Frete__c> freights = new List<Frete__c>{freight1, freight2};

        List<Database.SaveResult> results = Database.insert(freights, false);

        Test.stopTest();

        Assert.isTrue(results[0].isSuccess(), 'Houve erro no primeiro registro');
        Assert.isFalse(results[1].isSuccess(), 'A duplicata foi inserida');
        Assert.isTrue(results[1].getErrors().size() > 0, 'Não houve erro no registro duplicado');
        Assert.areEqual('Este frete é duplicata de outro nesta mesma inserção.', results[1].getErrors()[0].getMessage(), 'Mensagem de erro discrepante.');
    }


    @IsTest 
    static void testOrgDuplicityOnInsert() {
        Test.startTest();

        Frete__c freight1 = TestDataFactory.createFreight(true); 
        Frete__c freight2 = freight1.clone();

        Database.SaveResult result = Database.insert(freight2, false);

        Test.stopTest();

        Assert.isFalse(result.isSuccess(), 'A duplicata foi inserida');
        Assert.isTrue(result.getErrors().size() > 0, 'Não houve erro no registro duplicado');
        Assert.areEqual('Já existe um frete para esse produto/hierarquia e centro de dist. nessa localidade.', result.getErrors()[0].getMessage(), 'Mensagem de erro discrepante.');
    }

    @IsTest 
    static void testQuery() {
        Test.startTest();

        Product2 product = TestDataFactory.createProduct(true);
        Estado__c state = TestDataFactory.createState(true);
        DistributionCenter__c distCenter1 = TestDataFactory.createDistCenter(true);
        DistributionCenter__c distCenter2 = TestDataFactory.createDistCenter(true);

        Frete__c freight1 = TestDataFactory.createFreight(product.Id, state.Id, distCenter1.Id, true);
        Frete__c freight2 = TestDataFactory.createFreight(product.Id, state.Id, distCenter2.Id, true);

        List<Frete__c> freights = FreteHelper.queryFreightsWithFields(new Set<Id>(), new Set<Id>{state.Id}, new Set<Id>(), new Set<Id>{product.Id}, new Set<Id>(), new Set<Id>{distCenter1.Id});

        Test.stopTest();

        Assert.areEqual(1, freights.size(), 'A query não retornou apenas um registro');
        Assert.areEqual(freight1.Id, freights[0].Id, 'O registro retornado pela query não é o esperado');
    }

    @IsTest 
    static void testQueryApprovedWithBlockedRecord() {
        Test.startTest();

        Frete__c freight2 = TestDataFactory.createFreight(false);
        Frete__c freight1 = TestDataFactory.createFreight(false);
        freight2.Status__c = 'Bloqueado';
        Database.insert(new List<Frete__c>{freight1, freight2});

        List<Frete__c> freights = FreteHelper.queryApprovedFreightsWithFields(new Set<Id>{freight1.Cidade__c, freight2.Cidade__c}, new Set<Id>(), new Set<Id>(),new Set<Id>{freight1.Product__c, freight2.Product__c}, new Set<Id>(),new Set<Id>{freight1.CentroDistribuicao__c, freight2.CentroDistribuicao__c});

        Test.stopTest();

        Assert.areEqual(1, freights.size(), 'A query não retornou apenas um registro');
        Assert.areEqual(freight1.Id, freights[0].Id, 'O registro retornado pela query não é o esperado');
    }

    @IsTest 
    static void testGetStringKeyMap() {
        Test.startTest();

        Frete__c freight1 = TestDataFactory.createFreight(false);
        Frete__c freight2 = TestDataFactory.createFreight(false);
        List<Frete__c> freights = new List<Frete__c>{freight1, freight2};

        Map<String, Frete__c> mapStringKeyXFreight = FreteHelper.getMapStringKeyXFreight(freights);

        Test.stopTest();

        Assert.areEqual(freight1, mapStringKeyXFreight.get(KeyStringGenerator.createStringKeyFromIds(freight1.Cidade__c, freight1.Product__c, freight1.CentroDistribuicao__c)));
        Assert.areEqual(freight2, mapStringKeyXFreight.get(KeyStringGenerator.createStringKeyFromIds(freight2.Cidade__c, freight2.Product__c, freight2.CentroDistribuicao__c)));
    }
}