force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual é aplicado o imposto.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do imposto</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/ValorPercentual__c.field-meta.xml
<CustomField>
    <fullName>ValorPercentual__c</fullName>
    <description>Percentual de imposto acrescentada ao valor do produto.</description>
    <label>ValorPercentual</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/helper/ImpostoHelper.cls
public with sharing class ImpostoHelper {
    
    public static void impedirDuplicidade(List<Imposto__c> newImpostos) {
        Set<Id> idsEstado = new Set<Id>();
        Set<Id> idsProduto = new Set<Id>();
        Set<String> impostoPair = new Set<String>();

        for (Imposto__c imposto : newImpostos) {
            if (impostoPair.add(KeyStringGenerator.createStringFromKeys(imposto.Estado__c, imposto.Product__c))) {
                idsEstado.add(imposto.Estado__c);
                idsProduto.add(imposto.Product__c);
            } else {
                imposto.addError('Este imposto é duplicata de outro nesta mesma inserção.');
            }
        }

        Set<String> estadoProdutoPair = new Set<String>();
        for (Imposto__c impostosOrg : queryImpostoComEstadoProd(idsEstado, idsProduto)) {
            estadoProdutoPair.add(KeyStringGenerator.createStringFromKeys(impostosOrg.Estado__c, impostosOrg.Product__c));
        }

        for (Imposto__c newImposto : newImpostos) {
            if (estadoProdutoPair.contains(KeyStringGenerator.createStringFromKeys(newImposto.Estado__c, newImposto.Product__c))) {
                newImposto.addError('Já existe um imposto para esse produto nesse estado.');
                continue;
            }
        }
    }

    public static List<Imposto__c> queryImpostoComEstadoProd(Set<Id> idsEstado, Set<Id> idsProduto) {
        return [SELECT Id, Estado__c, Product__c, ValorPercentual__c 
                FROM Imposto__c 
                WHERE (Status__c = 'Aprovado' AND Estado__c IN :idsEstado AND Product__c IN :idsProduto)];
    }

}