force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Grupo ao qual pertence a conta.</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <description>Grupo de contas de clientes</description>
    <label>Account Group</label>
    <nameField>
        <label>AccountGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CentroDistribuicao__c/CentroDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável por frete.</description>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome do Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável pelo pedido.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição aonde o pedido será enviado.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia do produto (alternativo ao produto).</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto do frete (alternativo à hierarquia de produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HierarquiaProduto__c/HierarquiaProduto__c.object-meta.xml
<CustomObject>
    <description>Hierarquia a que produtos pertencem</description>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Nome da Hierarquia de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual é aplicado o imposto.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta associada à margem (alternativa ao grupo de contas).</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição associado à margem.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia sobre a qual é aplicada a margem (alternativa ao Produto)</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual a margem é aplicada (alternativo à Hierarquia de Produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>País</description>
    <label>País</label>
    <nameField>
        <label>Nome do País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/CustoProducao__c.field-meta.xml
<CustomField>
    <fullName>CustoProducao__c</fullName>
    <label>Custo de Produção</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hierarquia do produto</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {


    // +++++++++++++++++++++++++++++++++
    // Create AccountGroup
    // +++++++++++++++++++++++++++++++++

    public static AccountGroup__c createAccountGroup(Boolean doInsert) {
        AccountGroup__c accountGroup = (AccountGroup__c)TestFactorySObject.getInstance().createSObject(new AccountGroup__c());
        if (doInsert) {
            Database.insert(accountGroup);
        }

        return accountGroup;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Account
    // +++++++++++++++++++++++++++++++++

    public static Account createAccount(Id accountGroupId, Boolean doInsert) {
        Account account = (Account)TestFactorySObject.getInstance().createSObject(new Account(AccountGroup__c = accountGroupId));
        if (doInsert) {
            Database.insert(account);
        }

        return account;
    }

    public static Account createAccount(Boolean doInsert) {
        return createAccount(createAccountGroup(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create HierarquiaProduto
    // +++++++++++++++++++++++++++++++++

    public static HierarquiaProduto__c createProductHierarchy(Boolean doInsert) {
        HierarquiaProduto__c productHierarchy = (HierarquiaProduto__c)TestFactorySObject.getInstance().createSObject(new HierarquiaProduto__c());
        if (doInsert) {
            Database.insert(productHierarchy);
        }
        
        return productHierarchy;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Product
    // +++++++++++++++++++++++++++++++++

    public static Product2 createProduct(Id productHierarchyId, Boolean doInsert) {
        Product2 product = (Product2)TestFactorySObject.getInstance().createSObject(new Product2(HierarquiaProduto__c = productHierarchyId, CustoProducao__c = 5));
        if (doInsert) {
            TriggerHandler.bypass('ProductTriggerHandler');
            Database.insert(product);
            TriggerHandler.clearBypass('ProductTriggerHandler');
        }

        return product;
    }

    public static Product2 createProduct(Boolean doInsert) {
        return createProduct(createProductHierarchy(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Pais
    // +++++++++++++++++++++++++++++++++

    public static Pais__c createCountry(Boolean doInsert) {
        Pais__c country = (Pais__c)TestFactorySObject.getInstance().createSObject(new Pais__c());
        if (doInsert) {
            Database.insert(country);
        }

        return country;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Estado
    // +++++++++++++++++++++++++++++++++

    public static Estado__c createState(Id countryId, Boolean doInsert) {
        Estado__c state = (Estado__c)TestFactorySObject.getInstance().createSObject(new Estado__c(Pais__c = countryId));
        if (doInsert) {
            Database.insert(state);
        }

        return state;
    }

    public static Estado__c createState(Boolean doInsert) {
        return createState(createCountry(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Cidade
    // +++++++++++++++++++++++++++++++++

    public static Cidade__c createCity(Id stateId, Boolean doInsert) {
        Cidade__c city = (Cidade__c)TestFactorySObject.getInstance().createSObject(new Cidade__c(Estado__c = stateId));
        if (doInsert) {
            Database.insert(city);
        }

        return city;
    }

    public static Cidade__c createCity(Boolean doInsert) {
        return createCity(createState(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create DistributionCenter
    // +++++++++++++++++++++++++++++++++

    public static DistributionCenter__c createDistCenter(Boolean doInsert) {
        DistributionCenter__c distCenter = (DistributionCenter__c)TestFactorySObject.getInstance().createSObject(new DistributionCenter__c());
        if (doInsert) {
            Database.insert(distCenter);
        }

        return distCenter;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Imposto
    // +++++++++++++++++++++++++++++++++

    public static Imposto__c createTax(Id productId, Id stateId, Id distCenterId, Boolean doInsert) {
        Imposto__c tax = (Imposto__c)TestFactorySObject.getInstance().createSObject(new Imposto__c());
        tax.Product__c = productId;
        tax.Estado__c = stateId;
        tax.CentroDistribuicao__c = distCenterId;
        if (doInsert) {
            Database.insert(tax);
        }

        System.debug(tax);
        return tax;
    }

    public static Imposto__c createTax(Boolean doInsert) {
        return createTax(createProduct(true).Id, createState(true).Id, createDistCenter(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Frete
    // +++++++++++++++++++++++++++++++++

    public static Frete__c createFreight(Id productId, Id locationId, Id distCenterId, Boolean doInsert) {
        Frete__c freight = (Frete__c)TestFactorySObject.getInstance().createSObject(new Frete__c());

        if (productId.getSObjectType() == Product2.sObjectType) {
            freight.Product__c = productId;
        } else {
            freight.HierarquiaProduto__c = productId;
        }

        if (locationId.getSObjectType() == Cidade__c.sObjectType) {
            freight.Cidade__c = locationId;
        } else if (locationId.getSObjectType() == Estado__c.sObjectType) {
            freight.Estado__c = locationId;
        } else {
            freight.Pais__c = locationId;
        }

        freight.CentroDistribuicao__c = distCenterId;

        if (doInsert) {
            Database.insert(freight);
        }

        System.debug(freight);

        return freight;
    }

    public static Frete__c createFreight(Boolean doInsert) {
        return createFreight(createProduct(true).Id, createCity(true).Id, createDistCenter(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Margem
    // +++++++++++++++++++++++++++++++++

    public static Margem__c createMargin(Id productId, Id accountId, Id locationId, Id distCenterId, Boolean doInsert) {
        Margem__c margin = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c());

        if (productId.getSObjectType() == Product2.sObjectType) {
            margin.Product__c = productId;
        } else {
            margin.HierarquiaProduto__c = productId;
        }

        if (accountId.getSobjectType() == Account.sObjectType) {
            margin.Account__c = accountId;
        } else {
            margin.AccountGroup__c = accountId;
        }

        if (locationId.getSObjectType() == Cidade__c.sObjectType) {
            margin.Cidade__c = locationId;
        } else if (locationId.getSObjectType() == Estado__c.sObjectType) {
            margin.Estado__c = locationId;
        } else {
            margin.Pais__c = locationId;
        }

        margin.CentroDistribuicao__c = distCenterId;

        if (doInsert) {
            Database.insert(margin);
        }

        System.debug(margin);

        return margin;
    }

    public static Margem__c createMargin(Boolean doInsert) {
        return createMargin(createProduct(true).Id, createAccount(true).Id, createCity(true).Id, createDistCenter(true).Id, doInsert);
    }

}