force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Grupo ao qual pertence a conta.</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <description>Endereço associado a uma conta</description>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAddress__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cidade do endereço</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <description>Grupo de contas de clientes</description>
    <label>Account Group</label>
    <nameField>
        <label>AccountGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável pelo pedido.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor do frete calculado pela localidade informada.</description>
    <formula>IF(NOT(ISBLANK( Cidade__c )), 30, IF(NOT(ISBLANK( Estado__c )), 20, IF(NOT(ISBLANK( Pais__c )), 10, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/ValorPercentual__c.field-meta.xml
<CustomField>
    <fullName>ValorPercentual__c</fullName>
    <description>Percentual de imposto acrescentada ao valor do produto.</description>
    <label>ValorPercentual</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor da margem calculado pela localidade informada e pela especificidade da conta (conta ou hierarquia).</description>
    <formula>IF(NOT(ISBLANK( Account__c )), 200, IF(NOT(ISBLANK( Account_Group__c )), 100, 0)) 
+ 
IF(NOT(ISBLANK( Cidade__c )), 30, IF(NOT(ISBLANK( Estado__c )), 10, IF(NOT(ISBLANK( Pais__c )), 10, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Endereço do pedido</description>
    <label>Account Address</label>
    <referenceTo>AccountAddress__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ImpostoPercent__c.field-meta.xml
<CustomField>
    <fullName>ImpostoPercent__c</fullName>
    <description>Porcentagem de imposto aplicado sobre o item.</description>
    <label>Porcentagem de Imposto</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/MargemPercent__c.field-meta.xml
<CustomField>
    <fullName>MargemPercent__c</fullName>
    <description>Porcentagem de margem aplicada sobre o item.</description>
    <label>Porcentagem de Margem</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PrecoSemMargem__c.field-meta.xml
<CustomField>
    <fullName>PrecoSemMargem__c</fullName>
    <description>Preço do item excluindo a margem.</description>
    <formula>( ListPrice  +  ValorFrete__c) * (1 + ImpostoPercent__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço sem Margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ValorFrete__c.field-meta.xml
<CustomField>
    <fullName>ValorFrete__c</fullName>
    <description>Valor do frete para o item.</description>
    <label>Valor de Frete</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>País</description>
    <label>País</label>
    <nameField>
        <label>Nome do País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test/OrderItemTest.cls
@isTest
private class OrderItemTest {

    @isTest
    static void testSearchAndAssignParameters() {
        Test.startTest();

        Product2 product = TestDataFactory.createProduct(true);
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        Account account = TestDataFactory.createAccount(true);
        AccountAddress__c address = TestDataFactory.createAddress(account.Id, city.Id, true);
        DistributionCenter__c distCenter = TestDataFactory.createDistCenter(true);

        Imposto__c tax = TestDataFactory.createTax(product.Id, state.Id, distCenter.Id, true);
        Margem__c margin = TestDataFactory.createMargin(product.Id, account.AccountGroup__c, state.Pais__c, distCenter.Id, true);
        Frete__c freight = TestDataFactory.createFreight(product.Id, state.Pais__c, distCenter.Id, true);

        System.debug('Tax: ' + tax);

        Pricebook2 pricebook = PricebookHelper.getTestPricebook();
        Order order = TestDataFactory.createOrder(account.Id, address.Id, distCenter.Id, pricebook.Id, TestDataFactory.createPaymentCondition(true).Id, true);

        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(pricebook, product, true);

        OrderItem orderItem = TestDataFactory.createOrderItem(product.Id, order.Id, pricebookEntry, false);
        
        Database.SaveResult result = Database.insert(orderItem);

        OrderItem insertedItem = [SELECT Id, ImpostoPercent__c, ValorFrete__c, MargemPercent__c, PrecoSemMargem__c FROM OrderItem WHERE Id = :orderItem.Id LIMIT 1];

        Test.stopTest();

        Assert.isTrue(result.isSuccess(), 'Houve erro na atribuição de parâmetros');
        Assert.areEqual(tax.ValorPercentual__c, insertedItem.ImpostoPercent__c, 'O valor de imposto atribuído não é o esperado');
        Assert.areEqual(freight.Valor__c, insertedItem.ValorFrete__c, 'O valor de frete atribuído não é o esperado');
        Assert.areEqual(margin.Valor__c, (insertedItem.MargemPercent__c * insertedItem.PrecoSemMargem__c / 100).setScale(2), 'O valor de frete atribuído não é o esperado');
    }

    @isTest
    static void testSearchAndAssignParameterFail() {
        Test.startTest();

        Product2 product = TestDataFactory.createProduct(true);
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        Account account = TestDataFactory.createAccount(true);
        AccountAddress__c address = TestDataFactory.createAddress(account.Id, city.Id, true);
        DistributionCenter__c distCenter = TestDataFactory.createDistCenter(true);

        Imposto__c tax = TestDataFactory.createTax(product.Id, state.Id, distCenter.Id, true);
        // Margem faltante
        Frete__c freight = TestDataFactory.createFreight(product.Id, state.Pais__c, distCenter.Id, true);

        System.debug('Tax: ' + tax);

        Pricebook2 pricebook = PricebookHelper.getTestPricebook();
        Order order = TestDataFactory.createOrder(account.Id, address.Id, distCenter.Id, pricebook.Id, TestDataFactory.createPaymentCondition(true).Id, true);

        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(pricebook, product, true);

        OrderItem orderItem = TestDataFactory.createOrderItem(product.Id, order.Id, pricebookEntry, false);
        
        Database.SaveResult result = Database.insert(orderItem, false);

        Test.stopTest();

        Assert.isFalse(result.isSuccess(), 'O item não deveria ter sido inserido, pois não possui um dos parâmetros');
    }

}