force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Grupo ao qual pertence a conta.</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <description>Endereço associado a uma conta</description>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAddress__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cidade do endereço</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição aonde o pedido será enviado.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia do produto (alternativo ao produto).</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto do frete (alternativo à hierarquia de produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual é aplicado o imposto.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia sobre a qual é aplicada a margem (alternativa ao Produto)</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual a margem é aplicada (alternativo à Hierarquia de Produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CustoProducao__c.field-meta.xml
<CustomField>
    <fullName>CustoProducao__c</fullName>
    <description>Custo de produção do(s) item(s)</description>
    <formula>Product2.CustoProducao__c *  Quantity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Custo de Produção</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CustoProducao__c.field-meta.xml
<CustomField>
    <fullName>CustoProducao__c</fullName>
    <label>Custo de Produção</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hierarquia do produto</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/setup/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {


    // +++++++++++++++++++++++++++++++++
    // Create AccountGroup
    // +++++++++++++++++++++++++++++++++

    public static AccountGroup__c createAccountGroup(Boolean doInsert) {
        AccountGroup__c accountGroup = (AccountGroup__c)TestFactorySObject.getInstance().createSObject(new AccountGroup__c());
        if (doInsert) {
            Database.insert(accountGroup);
        }

        return accountGroup;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Account
    // +++++++++++++++++++++++++++++++++

    public static Account createAccount(Id accountGroupId, Boolean doInsert) {
        Account account = (Account)TestFactorySObject.getInstance().createSObject(new Account(AccountGroup__c = accountGroupId));
        if (doInsert) {
            Database.insert(account);
        }

        return account;
    }

    public static Account createAccount(Boolean doInsert) {
        return createAccount(createAccountGroup(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create HierarquiaProduto
    // +++++++++++++++++++++++++++++++++

    public static HierarquiaProduto__c createProductHierarchy(Boolean doInsert) {
        HierarquiaProduto__c productHierarchy = (HierarquiaProduto__c)TestFactorySObject.getInstance().createSObject(new HierarquiaProduto__c());
        if (doInsert) {
            Database.insert(productHierarchy);
        }
        
        return productHierarchy;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Product
    // +++++++++++++++++++++++++++++++++

    public static Product2 createProduct(Id productHierarchyId, Boolean doInsert) {
        Product2 product = (Product2)TestFactorySObject.getInstance().createSObject(new Product2(HierarquiaProduto__c = productHierarchyId, CustoProducao__c = 5));
        if (doInsert) {
            Database.insert(product);
        }

        return product;
    }

    public static Product2 createProduct(Boolean doInsert) {
        return createProduct(createProductHierarchy(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Pais
    // +++++++++++++++++++++++++++++++++

    public static Pais__c createCountry(Boolean doInsert) {
        Pais__c country = (Pais__c)TestFactorySObject.getInstance().createSObject(new Pais__c());
        if (doInsert) {
            Database.insert(country);
        }

        return country;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Estado
    // +++++++++++++++++++++++++++++++++

    public static Estado__c createState(Id countryId, Boolean doInsert) {
        Estado__c state = (Estado__c)TestFactorySObject.getInstance().createSObject(new Estado__c(Pais__c = countryId));
        if (doInsert) {
            Database.insert(state);
        }

        return state;
    }

    public static Estado__c createState(Boolean doInsert) {
        return createState(createCountry(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Cidade
    // +++++++++++++++++++++++++++++++++

    public static Cidade__c createCity(Id stateId, Boolean doInsert) {
        Cidade__c city = (Cidade__c)TestFactorySObject.getInstance().createSObject(new Cidade__c(Estado__c = stateId));
        if (doInsert) {
            Database.insert(city);
        }

        return city;
    }

    public static Cidade__c createCity(Boolean doInsert) {
        return createCity(createState(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create DistributionCenter
    // +++++++++++++++++++++++++++++++++

    public static DistributionCenter__c createDistCenter(Boolean doInsert) {
        DistributionCenter__c distCenter = (DistributionCenter__c)TestFactorySObject.getInstance().createSObject(new DistributionCenter__c());
        if (doInsert) {
            Database.insert(distCenter);
        }

        return distCenter;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Imposto
    // +++++++++++++++++++++++++++++++++

    public static Imposto__c createTax(Id productId, Id stateId, Id distCenterId, Boolean doInsert) {
        Imposto__c tax = (Imposto__c)TestFactorySObject.getInstance().createSObject(new Imposto__c());
        tax.Product__c = productId;
        tax.Estado__c = stateId;
        tax.CentroDistribuicao__c = distCenterId;
        if (doInsert) {
            Database.insert(tax);
        }

        System.debug(tax);
        return tax;
    }

    public static Imposto__c createTax(Boolean doInsert) {
        return createTax(createProduct(true).Id, createState(true).Id, createDistCenter(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Frete
    // +++++++++++++++++++++++++++++++++

    public static Frete__c createFreight(Id productId, Id locationId, Id distCenterId, Boolean doInsert) {
        Frete__c freight = (Frete__c)TestFactorySObject.getInstance().createSObject(new Frete__c());

        if (productId.getSObjectType() == Product2.sObjectType) {
            freight.Product__c = productId;
        } else {
            freight.HierarquiaProduto__c = productId;
        }

        if (locationId.getSObjectType() == Cidade__c.sObjectType) {
            freight.Cidade__c = locationId;
        } else if (locationId.getSObjectType() == Estado__c.sObjectType) {
            freight.Estado__c = locationId;
        } else {
            freight.Pais__c = locationId;
        }

        freight.CentroDistribuicao__c = distCenterId;

        if (doInsert) {
            Database.insert(freight);
        }

        System.debug(freight);

        return freight;
    }

    public static Frete__c createFreight(Boolean doInsert) {
        return createFreight(createProduct(true).Id, createCity(true).Id, createDistCenter(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create Margem
    // +++++++++++++++++++++++++++++++++

    public static Margem__c createMargin(Id productId, Id accountId, Id locationId, Id distCenterId, Boolean doInsert) {
        Margem__c margin = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c());

        if (productId.getSObjectType() == Product2.sObjectType) {
            margin.Product__c = productId;
        } else {
            margin.HierarquiaProduto__c = productId;
        }

        if (accountId.getSobjectType() == Account.sObjectType) {
            margin.Account__c = accountId;
        } else {
            margin.AccountGroup__c = accountId;
        }

        if (locationId.getSObjectType() == Cidade__c.sObjectType) {
            margin.Cidade__c = locationId;
        } else if (locationId.getSObjectType() == Estado__c.sObjectType) {
            margin.Estado__c = locationId;
        } else {
            margin.Pais__c = locationId;
        }

        margin.CentroDistribuicao__c = distCenterId;

        if (doInsert) {
            Database.insert(margin);
        }

        System.debug(margin);

        return margin;
    }

    public static Margem__c createMargin(Boolean doInsert) {
        return createMargin(createProduct(true).Id, createAccount(true).Id, createCity(true).Id, createDistCenter(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create AccountAddress
    // +++++++++++++++++++++++++++++++++

    public static AccountAddress__c createAddress(Id accountId, Id cidadeId, Boolean doInsert) {
        AccountAddress__c address = (AccountAddress__c)TestFactorySObject.getInstance().createSObject(new AccountAddress__c());
        address.Account__c = accountId;
        address.Cidade__c = cidadeId;

        if (doInsert) {
            Database.insert(address);
        }

        return address;
    }

    public static AccountAddress__c createAddress(Boolean doInsert) {
        return createAddress(createAccount(true).Id, createCity(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create CondicaoPagamento
    // +++++++++++++++++++++++++++++++++

    public static CondicaoPagamento__c createPaymentCondition(Boolean doInsert) {
        CondicaoPagamento__c condition = (CondicaoPagamento__c)TestFactorySObject.getInstance().createSObject(new CondicaoPagamento__c());

        if (doInsert) {
            Database.insert(condition);
        }

        return condition;
    }


    // +++++++++++++++++++++++++++++++++
    // Create Pricebook2
    // +++++++++++++++++++++++++++++++++

    public static Pricebook2 createPricebook(Boolean doInsert) {
        Pricebook2 pricebook = (Pricebook2)TestFactorySObject.getInstance().createSObject(new Pricebook2());
        if (doInsert) {
            Database.insert(pricebook);
        }

        return pricebook;
    }

    public static PricebookEntry createPricebookEntry(Pricebook2 pricebook, Product2 product, Boolean doInsert) {
        PricebookEntry pricebookEntry = PricebookHelper.createPricebookEntryForInsertion(pricebook, product);

        if (doInsert) {
            Database.insert(pricebookEntry);
        }

        return pricebookEntry;
    }    


    // +++++++++++++++++++++++++++++++++
    // Create Order
    // +++++++++++++++++++++++++++++++++

    public static Order createOrder(Id accountId, Id addressId, Id distCenterId, Id pricebookId, Id payConditionId, Boolean doInsert) {
        Order order = (Order)TestFactorySObject.getInstance().createSObject(new Order());
        order.AccountId = accountId;
        order.AccountAddress__c = addressId;
        order.CentroDistribuicao__c = distCenterId;
        order.Pricebook2Id = pricebookId;
        order.CondicaoPagamento__c = payConditionId;

        if (doInsert) {
            Database.insert(order);
        }

        return order;
    }

    public static Order createOrder(Boolean doInsert) {
        Account account = createAccount(true);
        return createOrder(account.Id, createAddress(account.Id, createCity(true).Id, true).Id, createDistCenter(true).Id, PricebookHelper.getStandardPricebook().Id, createPaymentCondition(true).Id, doInsert);
    }


    // +++++++++++++++++++++++++++++++++
    // Create OrderItem
    // +++++++++++++++++++++++++++++++++

    public static OrderItem createOrderItem(Id productId, Id orderId, PricebookEntry pricebookEntry, Boolean doInsert) {
        OrderItem orderItem = (OrderItem)TestFactorySObject.getInstance().createSObject(new OrderItem());
        orderItem.Product2Id = productId;
        orderItem.OrderId = orderId;
        orderItem.PricebookEntryId = priceBookEntry.Id;
        orderItem.ListPrice = pricebookEntry.UnitPrice;

        if(doInsert) {
            Database.insert(orderItem); 
        }

        return orderItem;
    }

    public static OrderItem createOrderItem(Boolean doInsert) {
        Account account = createAccount(true);
        Pricebook2 pricebook = PricebookHelper.getStandardPricebook();
        Order order = createOrder(account.Id, createAddress(account.Id, createCity(true).Id, true).Id, createDistCenter(true).Id, pricebook.Id, createPaymentCondition(true).Id, doInsert);
        TriggerHandler.bypass('ProductTriggerHandler');
        Product2 product = createProduct(true);
        TriggerHandler.bypass('ProductTriggerHandler');
        return createOrderItem(product.Id, createOrder(true).Id, createPricebookEntry(pricebook, product, true), doInsert);
    }
}