force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Grupo ao qual pertence a conta.</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <description>Endereço associado a uma conta</description>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAddress__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cidade do endereço</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <description>Grupo de contas de clientes</description>
    <label>Account Group</label>
    <nameField>
        <label>AccountGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável pelo pedido.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia do produto (alternativo ao produto).</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor do frete calculado pela localidade informada.</description>
    <formula>IF(NOT(ISBLANK( Cidade__c )), 30, IF(NOT(ISBLANK( Estado__c )), 20, IF(NOT(ISBLANK( Pais__c )), 10, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/HierarquiaProduto__c/HierarquiaProduto__c.object-meta.xml
<CustomObject>
    <description>Hierarquia a que produtos pertencem</description>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Nome da Hierarquia de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/ValorPercentual__c.field-meta.xml
<CustomField>
    <fullName>ValorPercentual__c</fullName>
    <description>Percentual de imposto acrescentada ao valor do produto.</description>
    <label>ValorPercentual</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia sobre a qual é aplicada a margem (alternativa ao Produto)</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor da margem calculado pela localidade informada e pela especificidade da conta (conta ou hierarquia).</description>
    <formula>IF(NOT(ISBLANK( Account__c )), 200, IF(NOT(ISBLANK( Account_Group__c )), 100, 0)) 
+ 
IF(NOT(ISBLANK( Cidade__c )), 30, IF(NOT(ISBLANK( Estado__c )), 10, IF(NOT(ISBLANK( Pais__c )), 10, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Endereço do pedido</description>
    <label>Account Address</label>
    <referenceTo>AccountAddress__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ImpostoPercent__c.field-meta.xml
<CustomField>
    <fullName>ImpostoPercent__c</fullName>
    <description>Porcentagem de imposto aplicado sobre o item.</description>
    <label>Porcentagem de Imposto</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/MargemPercent__c.field-meta.xml
<CustomField>
    <fullName>MargemPercent__c</fullName>
    <description>Porcentagem de margem aplicada sobre o item.</description>
    <label>Porcentagem de Margem</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ValorFrete__c.field-meta.xml
<CustomField>
    <fullName>ValorFrete__c</fullName>
    <description>Valor do frete para o item.</description>
    <label>Valor de Frete</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>País</description>
    <label>País</label>
    <nameField>
        <label>Nome do País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hierarquia do produto</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/PricingTest.cls
@IsTest
private with sharing class PricingTest {
    
    @IsTest 
    static void testGetMostSpecificFreight() {
        Test.startTest();

        TriggerHandler.bypass('ProductTriggerHandler');
        Product2 product = TestDataFactory.createProduct(true);
        TriggerHandler.clearBypass('ProductTriggerHandler');
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        city.Estado__r = state;
        DistributionCenter__c distCenter= TestDataFactory.createDistCenter(true);

        List<Frete__c> freights = new List<Frete__c>{
            TestDataFactory.createFreight(product.HierarquiaProduto__c, state.Pais__c, distCenter.Id, false),
            TestDataFactory.createFreight(product.HierarquiaProduto__c, state.Id, distCenter.Id, false),
            TestDataFactory.createFreight(product.HierarquiaProduto__c, city.Id, distCenter.Id, false),
            TestDataFactory.createFreight(product.Id, state.Pais__c, distCenter.Id, false),
            TestDataFactory.createFreight(product.Id, state.Id, distCenter.Id, false),
            TestDataFactory.createFreight(product.Id, city.Id, distCenter.Id, false)
        };

        Map<String, Frete__c> mapStringKeyXFrete = FreteHelper.getMapStringKeyXFreight(freights);

        Frete__c selectedFreight = PricingHelper.getApplicableFreight(mapStringKeyXFrete, product, city, distCenter.Id);

        Test.stopTest();

        Assert.areEqual(freights[5], selectedFreight, 'Não foi selecionado o frete mais específico.');
    }

    @IsTest 
    static void testGetMostSpecificMargin() {
        Test.startTest();

        TriggerHandler.bypass('ProductTriggerHandler');
        Product2 product = TestDataFactory.createProduct(true);
        TriggerHandler.clearBypass('ProductTriggerHandler');
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        city.Estado__r = state;
        Account account = TestDataFactory.createAccount(true);
        DistributionCenter__c distCenter= TestDataFactory.createDistCenter(true);

        List<Margem__c> margins = new List<Margem__c>{
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.AccountGroup__c, state.Pais__c, distCenter.Id, false),
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.AccountGroup__c, state.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.AccountGroup__c,city.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.Id, state.Pais__c, distCenter.Id, false),
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.Id, state.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.Id, city.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.Id, account.AccountGroup__c, state.Pais__c, distCenter.Id, false),
            TestDataFactory.createMargin(product.Id, account.AccountGroup__c, state.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.Id, account.AccountGroup__c,city.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.Id, account.Id, state.Pais__c, distCenter.Id, false),
            TestDataFactory.createMargin(product.Id, account.Id, state.Id, distCenter.Id, false),
            TestDataFactory.createMargin(product.Id, account.Id,city.Id, distCenter.Id, false)
        };

        Map<String, Margem__c> mapStringKeyXMargin = MargemHelper.getMapStringKeyXMargin(margins);

        Margem__c selectedMargin = PricingHelper.getApplicableMargin(mapStringKeyXMargin, product, city, account, distCenter.Id);

        Test.stopTest();

        Assert.areEqual(margins[11], selectedMargin, 'Não foi selecionada a margem mais específica.');
    }

    @IsTest 
    static void testGetLeastSpecificFreight() {
        Test.startTest();

        TriggerHandler.bypass('ProductTriggerHandler');
        Product2 product = TestDataFactory.createProduct(true);
        TriggerHandler.clearBypass('ProductTriggerHandler');
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        city.Estado__r = state;
        DistributionCenter__c distCenter= TestDataFactory.createDistCenter(true);

        List<Frete__c> freights = new List<Frete__c>{
            TestDataFactory.createFreight(product.HierarquiaProduto__c, state.Pais__c, distCenter.Id, false)
        };

        Map<String, Frete__c> mapStringKeyXFrete = FreteHelper.getMapStringKeyXFreight(freights);

        Frete__c selectedFreight = PricingHelper.getApplicableFreight(mapStringKeyXFrete, product, city, distCenter.Id);

        Test.stopTest();

        Assert.areEqual(freights[0], selectedFreight, 'Não foi selecionado frete.');
    }

    @IsTest 
    static void testGetLeastSpecificMargin() {
        Test.startTest();

        TriggerHandler.bypass('ProductTriggerHandler');
        Product2 product = TestDataFactory.createProduct(true);
        TriggerHandler.clearBypass('ProductTriggerHandler');
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        city.Estado__r = state;
        Account account = TestDataFactory.createAccount(true);
        DistributionCenter__c distCenter= TestDataFactory.createDistCenter(true);

        List<Margem__c> margins = new List<Margem__c>{
            TestDataFactory.createMargin(product.HierarquiaProduto__c, account.AccountGroup__c, state.Pais__c, distCenter.Id, false)
        };

        Map<String, Margem__c> mapStringKeyXMargin = MargemHelper.getMapStringKeyXMargin(margins);

        Margem__c selectedMargin = PricingHelper.getApplicableMargin(mapStringKeyXMargin, product, city, account, distCenter.Id);

        Test.stopTest();

        Assert.areEqual(margins[0], selectedMargin, 'Não foi selecionada a margem mais específica.');
    }

    @IsTest
    static void testAssignParameters() {
        Test.startTest();

        Product2 product = TestDataFactory.createProduct(true);
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        city.Estado__r = state;
        Account account = TestDataFactory.createAccount(true);
        AccountAddress__c address = TestDataFactory.createAddress(account.Id, city.Id, true);
        address.Cidade__r = city;
        DistributionCenter__c distCenter = TestDataFactory.createDistCenter(true);

        List<Imposto__c> taxes = new List<Imposto__c>{
            TestDataFactory.createTax(product.Id, state.Id, distCenter.Id, false)
        };

        List<Margem__c> margins = new List<Margem__c>{
            TestDataFactory.createMargin(product.Id, account.AccountGroup__c, state.Pais__c, distCenter.Id, false)
        };

        List<Frete__c> freights = new List<Frete__c>{
            TestDataFactory.createFreight(product.Id, state.Pais__c, distCenter.Id, false)
        };

        Pricebook2 pricebook = PricebookHelper.getTestPricebook();
        Order order = TestDataFactory.createOrder(account.Id, address.Id, distCenter.Id, pricebook.Id, TestDataFactory.createPaymentCondition(true).Id, true);
        Order.Account = account;
        Order.AccountAddress__r = address;

        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(pricebook, product, true);

        TriggerHandler.bypass('OrderItemTriggerHandler');
        OrderItem orderItem = TestDataFactory.createOrderItem(product.Id, order.Id, pricebookEntry, false);
        TriggerHandler.clearBypass('OrderItemTriggerHandler');

        orderItem.ListPrice = pricebookEntry.UnitPrice;

        Map<Id,Order> mapOrder = new Map<Id,Order>{order.Id => order};
        Map<Id,Product2> mapProduct = new Map<Id,Product2>{product.Id => product};
        List<OrderItem> items = new List<OrderItem>{orderItem};
        
        Set<OrderItem> errors = PricingHelper.assignParameters(items, ImpostoHelper.getMapStringKeyXTax(taxes), FreteHelper.getMapStringKeyXFreight(freights), MargemHelper.getMapStringKeyXMargin(margins), mapOrder, mapProduct);

        Test.stopTest();

        Assert.areEqual(0, errors.size(), 'A atribuição de parâmetros retornou erros.');
        Assert.areEqual(taxes[0].ValorPercentual__c, orderItem.ImpostoPercent__c, 'O valor de imposto atribuído não é o esperado');
        Assert.areEqual(freights[0].Valor__c, orderItem.ValorFrete__c, 'O valor de frete atribuído não é o esperado');
        Assert.areEqual(100 * margins[0].Valor__c / ((orderItem.ListPrice + orderItem.ValorFrete__c )*(1+ orderItem.ImpostoPercent__c / 100)), orderItem.MargemPercent__c, 'O valor de frete atribuído não é o esperado');
    }

    @IsTest
    static void testOrderCreation() {
        Order order = TestDataFactory.createOrder(true);
    }

    @IsTest(SeeAllData=true)
    static void testOrderItemCreation() {
        TriggerHandler.bypass('OrderItemTriggerHandler');
        OrderItem orderItem = TestDataFactory.createOrderItem(true);
        TriggerHandler.clearBypass('OrderItemTriggerHandler');
    }



}