force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Grupo ao qual pertence a conta.</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <description>Endereço associado a uma conta</description>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAddress__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cidade do endereço</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição aonde o pedido será enviado.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor do frete calculado pela localidade informada.</description>
    <formula>IF(NOT(ISBLANK( Cidade__c )), 30, IF(NOT(ISBLANK( Estado__c )), 20, IF(NOT(ISBLANK( Pais__c )), 10, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/ValorPercentual__c.field-meta.xml
<CustomField>
    <fullName>ValorPercentual__c</fullName>
    <description>Percentual de imposto acrescentada ao valor do produto.</description>
    <label>ValorPercentual</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição associado à margem.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Endereço do pedido</description>
    <label>Account Address</label>
    <referenceTo>AccountAddress__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição responsável pelo pedido.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ImpostoPercent__c.field-meta.xml
<CustomField>
    <fullName>ImpostoPercent__c</fullName>
    <description>Porcentagem de imposto aplicado sobre o item.</description>
    <label>Porcentagem de Imposto</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/MargemPercent__c.field-meta.xml
<CustomField>
    <fullName>MargemPercent__c</fullName>
    <description>Porcentagem de margem aplicada sobre o item.</description>
    <label>Porcentagem de Margem</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PrecoSemMargem__c.field-meta.xml
<CustomField>
    <fullName>PrecoSemMargem__c</fullName>
    <description>Preço do item excluindo a margem.</description>
    <formula>( ListPrice  +  ValorFrete__c) * (1 + ImpostoPercent__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço sem Margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ValorFrete__c.field-meta.xml
<CustomField>
    <fullName>ValorFrete__c</fullName>
    <description>Valor do frete para o item.</description>
    <label>Valor de Frete</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/test/OrderTest.cls
@isTest
private class OrderTest {

    @isTest 
    static void testUpdateActivated() {
        TriggerHandler.bypass('ProductTriggerHandler');
        Product2 product = TestDataFactory.createProduct(true);
        TriggerHandler.bypass('ProductTriggerHandler');
        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(PricebookHelper.getStandardPricebook(), product, true);
        Order order = TestDataFactory.createOrder(true);

        TriggerHandler.bypass('OrderItemTriggerHandler');
        OrderItem orderItem = TestDataFactory.createOrderItem(product.Id, order.Id, pricebookEntry, true);


        order.Status = 'Activated';
        Database.SaveResult activateOrderResult= Database.update(order, false);

        order.CentroDistribuicao__c = TestDataFactory.createDistCenter(true).Id;
        Database.SaveResult updateOrderResult = Database.update(order, false);

        TriggerHandler.clearBypass('OrderItemTriggerHandler');

        Assert.isTrue(activateOrderResult.isSuccess(), 'Não foi possível ativar o pedido');
        Assert.isFalse(updateOrderResult.isSuccess(), 'O pedido ativado foi atualizado');
        Assert.areEqual('O pedido está ativo e não pode ser alterado.', updateOrderResult.getErrors()[0].getMessage(), 'O erro esperado não foi lançado no pedido');    
    }

    @isTest
    static void testChangeAccount() {
        Order order = TestDataFactory.createOrder(true);

        order.AccountId = TestDataFactory.createAccount(true).Id;
        Database.SaveResult updateOrderAccountResult = Database.update(order, false);


        Assert.isFalse(updateOrderAccountResult.isSuccess(), 'A conta do pedido foi atualizada');
        Assert.areEqual('A conta do pedido não pode ser alterada.', updateOrderAccountResult.getErrors()[0].getMessage(), 'O erro esperado não foi lançado no pedido');    
    }


    @isTest
    static void testUpdateParameters() {
        Test.startTest();

        Product2 product = TestDataFactory.createProduct(true);
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        Account account = TestDataFactory.createAccount(true);
        AccountAddress__c address = TestDataFactory.createAddress(account.Id, city.Id, true);
        DistributionCenter__c distCenter1 = TestDataFactory.createDistCenter(true);
        DistributionCenter__c distCenter2 = TestDataFactory.createDistCenter(true);

        List<Imposto__c> taxes = new List<Imposto__c>{
            TestDataFactory.createTax(product.Id, state.Id, distCenter1.Id, false),
            TestDataFactory.createTax(product.Id, state.Id, distCenter2.Id, false)
        };
        Database.insert(taxes);
        List<Frete__c> freights = new List<Frete__c>{
            TestDataFactory.createFreight(product.Id, state.Pais__c, distCenter1.Id, false),
            TestDataFactory.createFreight(product.Id, state.Pais__c, distCenter2.Id, false)
        };
        Database.insert(freights);
        List<Margem__c> margins = new List<Margem__c>{
            TestDataFactory.createMargin(product.Id, account.AccountGroup__c, state.Pais__c, distCenter1.Id, false),
            TestDataFactory.createMargin(product.Id, account.AccountGroup__c, state.Pais__c, distCenter2.Id, false)
        };
        Database.insert(margins);

        Pricebook2 pricebook = PricebookHelper.getTestPricebook();
        Order order = TestDataFactory.createOrder(account.Id, address.Id, distCenter1.Id, pricebook.Id, TestDataFactory.createPaymentCondition(true).Id, true);

        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(pricebook, product, true);

        OrderItem orderItem = TestDataFactory.createOrderItem(product.Id, order.Id, pricebookEntry, true);

        order.CentroDistribuicao__c = distCenter2.Id;
        Database.SaveResult result = Database.update(order, false);

        OrderItem insertedItem = [SELECT Id, ImpostoPercent__c, ValorFrete__c, MargemPercent__c, PrecoSemMargem__c FROM OrderItem WHERE Id = :orderItem.Id LIMIT 1];

        Test.stopTest();

        Assert.isTrue(result.isSuccess(), 'Houve erro na atribuição de parâmetros');
        Assert.areEqual(taxes[1].ValorPercentual__c, insertedItem.ImpostoPercent__c, 'O valor de imposto atribuído não é o esperado');
        Assert.areEqual(freights[1].Valor__c, insertedItem.ValorFrete__c, 'O valor de frete atribuído não é o esperado');
        Assert.areEqual(margins[1].Valor__c, (insertedItem.MargemPercent__c * insertedItem.PrecoSemMargem__c / 100).setScale(2), 'O valor de margem atribuído não é o esperado');   
    }

    @isTest
    static void testUpdateParametersFail() {
        Test.startTest();

        Product2 product1 = TestDataFactory.createProduct(true);
        Product2 product2 = TestDataFactory.createProduct(true);
        Estado__c state = TestDataFactory.createState(true);
        Cidade__c city = TestDataFactory.createCity(state.Id, true);
        Account account = TestDataFactory.createAccount(true);
        AccountAddress__c address = TestDataFactory.createAddress(account.Id, city.Id, true);
        DistributionCenter__c distCenter1 = TestDataFactory.createDistCenter(true);
        DistributionCenter__c distCenter2 = TestDataFactory.createDistCenter(true);

        List<Imposto__c> taxes = new List<Imposto__c>{
            TestDataFactory.createTax(product1.Id, state.Id, distCenter1.Id, false),
            TestDataFactory.createTax(product2.Id, state.Id, distCenter1.Id, false),
            TestDataFactory.createTax(product2.Id, state.Id, distCenter2.Id, false)
        };
        Database.insert(taxes);
        List<Frete__c> freights = new List<Frete__c>{
            TestDataFactory.createFreight(product1.Id, state.Pais__c, distCenter1.Id, false),
            TestDataFactory.createFreight(product1.Id, state.Pais__c, distCenter2.Id, false),
            TestDataFactory.createFreight(product2.Id, state.Pais__c, distCenter1.Id, false),
            TestDataFactory.createFreight(product2.Id, state.Pais__c, distCenter2.Id, false)
        };
        Database.insert(freights);
        List<Margem__c> margins = new List<Margem__c>{
            TestDataFactory.createMargin(product1.Id, account.AccountGroup__c, state.Pais__c, distCenter1.Id, false),
            TestDataFactory.createMargin(product1.Id, account.AccountGroup__c, state.Pais__c, distCenter2.Id, false),
            TestDataFactory.createMargin(product2.Id, account.AccountGroup__c, state.Pais__c, distCenter1.Id, false),
            TestDataFactory.createMargin(product2.Id, account.AccountGroup__c, state.Pais__c, distCenter2.Id, false)
        };
        Database.insert(margins);

        Pricebook2 pricebook = PricebookHelper.getTestPricebook();
        Order order = TestDataFactory.createOrder(account.Id, address.Id, distCenter1.Id, pricebook.Id, TestDataFactory.createPaymentCondition(true).Id, true);

        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(pricebook, product1, true);

        OrderItem orderItem2 = TestDataFactory.createOrderItem(product2.Id, order.Id, pricebookEntry, true);
        OrderItem orderItem3 = TestDataFactory.createOrderItem(product2.Id, order.Id, pricebookEntry, true);
        OrderItem orderItem4 = TestDataFactory.createOrderItem(product2.Id, order.Id, pricebookEntry, true);
        OrderItem orderItem1 = TestDataFactory.createOrderItem(product1.Id, order.Id, pricebookEntry, true);


        order.CentroDistribuicao__c = distCenter2.Id;
        Database.SaveResult result = Database.update(order, false);

        OrderItem insertedItem = [SELECT Id, ImpostoPercent__c, ValorFrete__c, MargemPercent__c, PrecoSemMargem__c FROM OrderItem WHERE Id = :orderItem2.Id LIMIT 1];

        Test.stopTest();

        Assert.isFalse(result.isSuccess(), 'A alteração ocorreu');
        Assert.areEqual('Esta alteração foi abortada, pois algum dos itens ficaria sem parâmetros de precificação.', result.getErrors()[0].getMessage());
        Assert.areEqual(taxes[0].ValorPercentual__c, insertedItem.ImpostoPercent__c, 'O valor de imposto foi alterado');
        Assert.areEqual(freights[0].Valor__c, insertedItem.ValorFrete__c, 'O valor de frete foi alterado');
        Assert.areEqual(margins[0].Valor__c, (insertedItem.MargemPercent__c * insertedItem.PrecoSemMargem__c / 100).setScale(2), 'O valor de margem foi alterado');   
    }

}