force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Grupo ao qual pertence a conta.</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <description>Endereço associado a uma conta</description>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAddress__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cidade do endereço</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <description>Grupo de contas de clientes</description>
    <label>Account Group</label>
    <nameField>
        <label>AccountGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CentroDistribuicao__c/CentroDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável por frete.</description>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome do Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/Frete__c.object-meta.xml
<CustomObject>
    <description>Dados de frete.</description>
    <label>Frete</label>
    <nameField>
        <label>Nome do Frete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Frete__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição aonde o pedido será enviado.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade para entrega.</description>
    <label>Cidade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Cidade__c.Estado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da entrega</description>
    <label>Estado</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Estado não existe para país selecionado</errorMessage>
        <filterItems>
            <field>Estado__c.Pais__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia do produto (alternativo ao produto).</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Frete__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da entrega.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Fretes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HierarquiaProduto__c/HierarquiaProduto__c.object-meta.xml
<CustomObject>
    <description>Hierarquia a que produtos pertencem</description>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Nome da Hierarquia de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/Imposto__c.object-meta.xml
<CustomObject>
    <description>Imposto aplicado sobre um produto.</description>
    <label>Imposto</label>
    <nameField>
        <displayFormat>IMPOSTO-{0}</displayFormat>
        <label>Nome do Imposto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impostos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado que aplica o imposto.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição associado à margem.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia sobre a qual é aplicada a margem (alternativa ao Produto)</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Endereço do pedido</description>
    <label>Account Address</label>
    <referenceTo>AccountAddress__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição responsável pelo pedido.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ValorFrete__c.field-meta.xml
<CustomField>
    <fullName>ValorFrete__c</fullName>
    <description>Valor do frete para o item.</description>
    <label>Valor de Frete</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>País</description>
    <label>País</label>
    <nameField>
        <label>Nome do País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hierarquia do produto</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/helper/OrderItemHelper.cls
public with sharing class OrderItemHelper {
    
    public static void searchAndAssignParameters(List<OrderItem> items) {

        Set<Id> productIds = new Set<Id>();
        Set<Id> orderIds = new Set<Id>();
        for (OrderItem item : items) {
            productIds.add(item.Product2Id);
            orderIds.add(item.OrderId);
        }

        // Busca dos atributos relevantes dos pedidos relacionados
        Map<Id,Order> mapOrder = new Map<Id,Order>();
        Set<Id> cityIds = new Set<Id>();
        Set<Id> stateIds = new Set<Id>();
        Set<Id> countryIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> accountGroupIds = new Set<Id>();
        Set<Id> distCenterIds = new Set<Id>();
        for (Order order : OrderHelper.queryOrdersWithIds(orderIds)) {
            mapOrder.put(order.Id, order);
            cityIds.add(order.AccountAddress__r.Cidade__c);
            stateIds.add(order.AccountAddress__r.Cidade__r.Estado__c);
            countryIds.add(order.AccountAddress__r.Cidade__r.Estado__r.Pais__c);
            accountIds.add(order.AccountId);
            accountGroupIds.add(order.Account.AccountGroup__c);
            distCenterIds.add(order.CentroDistribuicao__c);
        }

        // Busca dos atributos relevantes dos produtos relacionados
        Map<Id,Product2> mapProduct = new Map<Id,Product2>();
        Set<Id> prodHierarchyIds = new Set<Id>();
        for (Product2 product : ProductHelper.queryProductsWithIds(productIds)) {
            mapProduct.put(product.Id, product);
            prodHierarchyIds.add(product.HierarquiaProduto__c);
        }

        // Busca dos parâmetros de preço correspondentes aos atributos
        Map<String, Imposto__c> mapStringKeyXTax = ImpostoHelper.getMapStringKeyXTax(ImpostoHelper.queryApprovedTaxesWithFields(cityIds, productIds, distCenterIds));
        Map<String, Frete__c> mapStringKeyXFreight = FreteHelper.getMapStringKeyXFreight(FreteHelper.queryApprovedFreightsWithFields(cityIds, stateIds, countryIds, productIds, prodHierarchyIds, distCenterIds));
        Map<String, Margem__c> mapStringKeyXMargin = MargemHelper.getMapStringKeyXMargin(MargemHelper.queryApprovedMarginWithFields(cityIds, stateIds, countryIds, productIds, prodHierarchyIds, accountIds, accountGroupIds, distCenterIds));

        // Atribuição dos parâmetros correspondentes aos fretes
        Set<OrderItem> itemsWithError = PricingHelper.assignParameters(items, mapStringKeyXTax, mapStringKeyXFreight, mapStringKeyXMargin, mapOrder, mapProduct);

        // Atribuição de erros de DML aos itens com erros
        for (OrderItem item : itemsWithError) {
            item.addError('Não está autorizada a venda deste produto devido à falta de parâmetros. Contate o time de Pricing');
        }
    }


    public static List<OrderItem> queryOrderItemsWithOrderIds(Set<Id> idsOrder) {
        return [SELECT Id, OrderId, ListPrice, ValorFrete__c, Product2Id, Product2.HierarquiaProduto__c
                FROM OrderItem
                WHERE OrderId IN :idsOrder];
    }
    
}