force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <description>Grupo de contas de clientes</description>
    <label>Account Group</label>
    <nameField>
        <label>AccountGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CentroDistribuicao__c/CentroDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável por frete.</description>
    <label>Centro de Distribuição</label>
    <nameField>
        <label>Nome do Centro de Distribuição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de Distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <description>Cidade</description>
    <label>Cidade</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Estado onde se encontra a cidade.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <description>Estado ou Unidade Federativa.</description>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>País a que pertence o estado.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HierarquiaProduto__c/HierarquiaProduto__c.object-meta.xml
<CustomObject>
    <description>Hierarquia a que produtos pertencem</description>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Nome da Hierarquia de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/Margem__c.object-meta.xml
<CustomObject>
    <description>Margem de lucro aplicada sobre um produto.</description>
    <label>Margem</label>
    <nameField>
        <displayFormat>MARGEM-{0}</displayFormat>
        <label>Nome da Margem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta associada à margem (alternativa ao grupo de contas).</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo de contas associado à margem (alternativo à conta).</description>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Centro de distribuição associado à margem.</description>
    <label>Centro de Distribuição</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cidade onde é aplicada a margem.</description>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado da margem.</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/HierarquiaProduto__c.field-meta.xml
<CustomField>
    <fullName>HierarquiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hierarquia sobre a qual é aplicada a margem (alternativa ao Produto)</description>
    <label>Hierarquia de Produto</label>
    <referenceTo>HierarquiaProduto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>País da margem.</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens (País)</relationshipLabel>
    <relationshipName>Margens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Produto sobre o qual a margem é aplicada (alternativo à Hierarquia de Produto).</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da margem.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <description>Valor da margem calculado pela localidade informada e pela especificidade da conta (conta ou hierarquia).</description>
    <formula>IF(NOT(ISBLANK( Account__c )), 200, IF(NOT(ISBLANK( Account_Group__c )), 100, 0)) 
+ 
IF(NOT(ISBLANK( Cidade__c )), 30, IF(NOT(ISBLANK( Estado__c )), 10, IF(NOT(ISBLANK( Pais__c )), 10, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>País</description>
    <label>País</label>
    <nameField>
        <label>Nome do País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/helper/MargemHelper.cls
public with sharing class MargemHelper {

    public static void impedirDuplicidade(List<Margem__c> newMargens) {
        Set<Id> idsLocalidade = new Set<Id>();
        Set<Id> idsProduto = new Set<Id>();
        Set<Id> idsCentroDist = new Set<Id>();
        Set<Id> idsConta = new Set<Id>();
        Set<String> margemLocProdAccString = new Set<String>();

        // Buscar ids dos atributos e validando duplicatas na mesma carga
        for (Margem__c margem : newMargens) {
            Id localidade = getLocalidadeId(margem);
            Id produto = getProdutoId(margem);
            Id conta = getContaId(margem);

            if (margemLocProdAccString.add(KeyStringGenerator.createStringKeyFromIds(localidade, produto, conta, margem.CentroDistribuicao__c))) {
                idsLocalidade.add(localidade);
                idsProduto.add(produto);
                idsConta.add(conta);
                idsCentroDist.add(margem.CentroDistribuicao__c);
            } else {
                margem.addError('Esta margem é duplicata de outra nesta mesma inserção.');
            }
        }

        // Buscar registros com os mesmos atributos 
        Set<String> locProdutoPairOrg = new Set<String>();
        for (Margem__c margemOrg : queryMargemComParametros(idsLocalidade,idsLocalidade, idsLocalidade, idsProduto, idsProduto, idsConta, idsConta, idsCentroDist)) {
            locProdutoPairOrg.add(KeyStringGenerator.createStringKeyFromIds(getLocalidadeId(margemOrg), getProdutoId(margemOrg), getContaId(margemOrg), margemOrg.CentroDistribuicao__c));
        }

        // Comparar novos registros com os da org, barrando duplicatas
        for (Margem__c newMargem : newMargens) {
            if (locProdutoPairOrg.contains(KeyStringGenerator.createStringKeyFromIds(getLocalidadeId(newMargem), getProdutoId(newMargem), getContaId(newMargem), newMargem.CentroDistribuicao__c))) {
                newMargem.addError('Já existe uma margem para esse produto/hierarquia e conta/grupo nesse estado.');
                continue;
            }
        }
    }

    
    public static Id getLocalidadeId(Margem__c margem) {
        return String.isNotBlank(margem.Cidade__c) ? 
                margem.Cidade__c : 
                String.isNotBlank(margem.Estado__c) ? 
                    margem.Estado__c : 
                    margem.Pais__c;
    }

    public static Id getProdutoId(Margem__c margem) {
        return String.isNotBlank(margem.Product__c) ? margem.Product__c : margem.HierarquiaProduto__c;
    }

    public static Id getContaId(Margem__c margem) {
        return String.isNotBlank(margem.Account__c) ? margem.Account__c : margem.AccountGroup__c;
    }

    public static List<Margem__c> queryMargemComParametros(Set<Id> idsCidade, Set<Id> idsEstado, Set<Id> idsPais, Set<Id> idsProduto, Set<Id> idsHierarquia, Set<Id> idsConta, Set<Id> idsGrupo, Set<Id> idsCentroDist) {
        return [SELECT Id, 
                Cidade__c, Estado__c, Pais__c, 
                Product__c, HierarquiaProduto__c, 
                Account__c, AccountGroup__c, 
                Valor__c 
                FROM Margem__c 
                WHERE ((Cidade__c IN :idsCidade OR Estado__c IN :idsEstado OR Pais__c IN :idsPais) AND 
                    (Product__c IN :idsProduto OR HierarquiaProduto__c IN :idsHierarquia) AND 
                    (Account__c IN :idsConta OR AccountGroup__c IN :idsGrupo) AND
                    CentroDistribuicao__c IN :idsCentroDist)];
    }

    public static List<Margem__c> queryMargemAprovadaComParametros(Set<Id> idsCidade, Set<Id> idsEstado, Set<Id> idsPais, Set<Id> idsProduto, Set<Id> idsHierarquia, Set<Id> idsConta, Set<Id> idsGrupo, Set<Id> idsCentroDist) {
        return [SELECT Id, 
                Cidade__c, Estado__c, Pais__c, 
                Product__c, HierarquiaProduto__c, 
                Account__c, AccountGroup__c,
                CentroDistribuicao__c,
                Valor__c 
                FROM Margem__c 
                WHERE (Status__c = 'Aprovado' AND 
                    (Cidade__c IN :idsCidade OR Estado__c IN :idsEstado OR Pais__c IN :idsPais) AND 
                    (Product__c IN :idsProduto OR HierarquiaProduto__c IN :idsHierarquia) AND 
                    (Account__c IN :idsConta OR AccountGroup__c IN :idsGrupo) AND
                    CentroDistribuicao__c IN :idsCentroDist)];
    }

    public static Map<String, Margem__c> getMapKeyXMargem(List<Margem__c> margens) {
        Map<String, Margem__c> mapLocProdAccXMargem = new Map<String, Margem__c>();
        for (Margem__c margem : margens) {
            Id idLocalidade = getLocalidadeId(margem);
            Id idProduto = getProdutoId(margem);
            Id idConta = getContaId(margem);
            Id idCentroDist = margem.CentroDistribuicao__c;
            mapLocProdAccXMargem.put(KeyStringGenerator.createStringKeyFromIds(idLocalidade, idProduto, idConta, idCentroDist), margem);
        }

        return mapLocProdAccXMargem;
    } 
}