force-app/main/default/objects/AccountAddress__c/AccountAddress__c.object-meta.xml
<CustomObject>
    <description>Endereço associado a uma conta</description>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <description>Condição de pagamento (à vista, parcelado, etc.).</description>
    <label>Condição de Pagamento</label>
    <nameField>
        <label>Nome da Condição de Pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>Centro de distribuiçao resposável pelo pedido.</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/AccountAddress__c.field-meta.xml
<CustomField>
    <fullName>AccountAddress__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Endereço do pedido</description>
    <label>Account Address</label>
    <referenceTo>AccountAddress__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Condição aplicada ao pagamento do pedido.</description>
    <label>Condição de Pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/batch/DeleteOldOrdersTest.cls
@isTest
private class DeleteOldOrdersTest {

    @TestSetup
    static void makeData(){
        Account account = TestDataFactory.createAccount(true);
        AccountAddress__c address = TestDataFactory.createAddress(account.Id, TestDataFactory.createCity(true).Id, true);
        DistributionCenter__c distCenter = TestDataFactory.createDistCenter(true);
        CondicaoPagamento__c paymentCondition = TestDataFactory.createPaymentCondition(true);

        List<Order> orders = new List<Order>();
        for (Integer i = 0; i < 90; i++) {
            orders.add(TestDataFactory.createOrder(account.Id, address.Id, distCenter.Id, Test.getStandardPricebookId(), paymentCondition.Id, false));
        }

        TriggerHandler.bypass('OrderTriggerHandler');
        Database.insert(orders);

        for (Integer i = 0; i < 45; i++) {
            Test.setCreatedDate(orders[i].Id, Datetime.now().addMonths(-6));
        }
        TriggerHandler.clearBypass('OrderTriggerHandler');
    }

    @isTest
    static void testDeleteOldOrdersBatch() {
        Test.startTest();
        DeleteOldOrders deletionBatch = new DeleteOldOrders(5);
        Id batchJobId = Database.executeBatch(deletionBatch);
        Test.stopTest();

        Assert.areEqual(0, [SELECT COUNT() FROM Order WHERE CreatedDate < :(Datetime.now().addMonths(-5))]);
        Assert.areEqual(45, [SELECT COUNT() FROM Order]);
    }

    @isTest
    static void testScheduledDeleteOldOrders() {
        Test.startTest();
        String cronExpression = '0 0 0 15 3 ? 2042';
        Id jobId = System.schedule('deleteOldOrdersTest', cronExpression, new ScheduledDeleteOldOrder());
        Test.stopTest();

        CronTrigger ct = [SELECT Id, CronExpression, State 
                            FROM CronTrigger 
                            WHERE Id = :jobId];
        Assert.areEqual(cronExpression, ct.CronExpression);
        Assert.areEqual('WAITING', ct.State);
    }
}