force-app/main/default/objects/DevParameters__mdt/DevParameters__mdt.object-meta.xml
<CustomObject>
    <description>Tabela para armazenar os parâmetros a serem utilizados nos desenvolvimentos</description>
    <label>Parâmetros de Desenvolvimento</label>
    <pluralLabel>Parâmetros de Desenvolvimento</pluralLabel>
</CustomObject>

force-app/main/default/objects/DevParameters__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/scheduled/ScheduledDeleteOldOrder.cls
public with sharing class ScheduledDeleteOldOrder implements Schedulable{

    public void execute(SchedulableContext context) {
        DevParameters__mdt parameter = [SELECT DeveloperName, Value__c 
                                        FROM DevParameters__mdt 
                                        WHERE DeveloperName = 'MaxNumberMonthsOrder' 
                                        LIMIT 1];
        Integer maxMonths = Integer.valueOf(parameter.Value__c);
        DeleteOldOrders deleteOldOrdersBatch = new DeleteOldOrders(maxMonths);
        Database.executeBatch(deleteOldOrdersBatch, 10);
    }

}