force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <label>Nome da Meta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/SalesTotalValue__c.field-meta.xml
<CustomField>
    <fullName>SalesTotalValue__c</fullName>
    <label>Valor de Vendas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/GoalItem__c.object-meta.xml
<CustomObject>
    <label>Item da Meta</label>
    <nameField>
        <label>Nome do Item da Meta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Meta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GoalItem__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Meta</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>Itens da Meta</relationshipLabel>
    <relationshipName>GoalItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>PaymentCondition__c</referenceTo>
    <relationshipLabel>Itens da Meta</relationshipLabel>
    <relationshipName>GoalItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da Meta</relationshipLabel>
    <relationshipName>GoalItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>ProductFamily__c</referenceTo>
    <relationshipLabel>Itens da Meta</relationshipLabel>
    <relationshipName>GoalItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/ProjectedValue__c.field-meta.xml
<CustomField>
    <fullName>ProjectedValue__c</fullName>
    <label>Valor Projetado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/recordTypes/PaymentCondition.recordType-meta.xml
<RecordType>
    <fullName>PaymentCondition</fullName>
    <active>true</active>
    <label>Condição de Pagamento</label>
</RecordType>

force-app/main/default/objects/GoalItem__c/recordTypes/ProductFamily.recordType-meta.xml
<RecordType>
    <fullName>ProductFamily</fullName>
    <active>true</active>
    <label>Família de Produto</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>PaymentCondition__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>PaymentCondition__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentCondition__c/PaymentCondition__c.object-meta.xml
<CustomObject>
    <label>Condição de Pagamento</label>
    <nameField>
        <label>Nome da Condição de Pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Família de Produto</label>
    <referenceTo>ProductFamily__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductFamily__c/ProductFamily__c.object-meta.xml
<CustomObject>
    <label>Família de Produto</label>
    <nameField>
        <label>Nome da Família de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Famílias de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GoalRefreshHelper.cls
public with sharing class GoalRefreshHelper {
    
    public static void setOrderItemValueToGoalItems(List<GoalItem__c> goalItemList, OrderItem orderItem, String valueFieldName) {

        for (GoalItem__c iGoalItem : goalItemList) {
            if (!iGoalItem.isSet(valueFieldName)) {
                iGoalItem.put(valueFieldName, 0);
            }

            System.debug(iGoalItem.RecordType);

            if (iGoalItem.RecordType.DeveloperName == 'Performance') {
                iGoalItem.put(valueFieldName, (Decimal) iGoalItem.get(valueFieldName) + orderItem.TotalPrice);
                continue;
            }

            if (iGoalItem.RecordType.DeveloperName == 'Product'
                    && iGoalItem.Product__c == orderItem.Product2Id) {
                iGoalItem.put(valueFieldName, (Decimal) iGoalItem.get(valueFieldName) + orderItem.TotalPrice);
                continue;
            }

            if (iGoalItem.RecordType.DeveloperName == 'ProductFamily'
                    && iGoalItem.ProductFamily__c == orderItem.Product2.ProductFamily__c) {
                iGoalItem.put(valueFieldName, (Decimal) iGoalItem.get(valueFieldName) + orderItem.TotalPrice);
                continue;
            }

            if (iGoalItem.RecordType.DeveloperName == 'PaymentCondition'
                    && iGoalItem.PaymentCondition__c == orderItem.Order.PaymentCondition__c) {
                iGoalItem.put(valueFieldName, (Decimal) iGoalItem.get(valueFieldName) + orderItem.TotalPrice);
                continue;
            }
        }

    }

    public static void setOppItemValueToGoalItems(List<GoalItem__c> goalItemList, OpportunityLineItem oppItem) {

        for (GoalItem__c iGoalItem : goalItemList) {
            if (!iGoalItem.isSet('ProjectedValue__c')) {
                iGoalItem.ProjectedValue__c = 0;
            }

            System.debug(iGoalItem.RecordType);

            if (iGoalItem.RecordType.DeveloperName == 'Performance') {
                iGoalItem.ProjectedValue__c += oppItem.TotalPrice;
                continue;
            }

            if (iGoalItem.RecordType.DeveloperName == 'Product'
                    && iGoalItem.Product__c == oppItem.Product2Id) {
                iGoalItem.ProjectedValue__c += oppItem.TotalPrice;
                continue;
            }

            if (iGoalItem.RecordType.DeveloperName == 'ProductFamily'
                    && iGoalItem.ProductFamily__c == oppItem.Product2.ProductFamily__c) {
                iGoalItem.ProjectedValue__c += oppItem.TotalPrice;
                continue;
            }

            if (iGoalItem.RecordType.DeveloperName == 'PaymentCondition'
                    && iGoalItem.PaymentCondition__c == oppItem.Opportunity.PaymentCondition__c) {
                iGoalItem.ProjectedValue__c += oppItem.TotalPrice;
                continue;
            }
        }

        System.debug(goalItemList);

    }

    public static void setOrderItemValueToGoals(List<Goal__c> goalList, OrderItem orderItem) {

        for (Goal__c iGoal : goalList) {
            if (!iGoal.isSet('SalesTotalValue__c')) {
                iGoal.SalesTotalValue__c = 0;
            }

            iGoal.SalesTotalValue__c += orderItem.TotalPrice;
        }

    }

}